version: '3'

services:
    postgres:
        image: postgres:9.6
        environment:
            POSTGRES_PASSWORD: hola
            POSTGRES_USER: hola
            POSTGRES_DB: holadb
        ports:
            - "5434:5432" 
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
          - .:/mysite
        ports:
          - "8000:8000"
        depends_on:
          - postgres
